from langchain_community.document_loaders import TextLoader

loader=TextLoader("spiderman.txt", encoding='utf-8')
docs=loader.load()
print(docs)
print("--------------------------------------------------------------")
print(type(docs))
print("--------------------------------------------------------------")
print(len(docs))
print("--------------------------------------------------------------")
print(docs[0])
print("--------------------------------------------------------------")
print(type(docs[0]))
print("--------------------------------------------------------------")
print(docs[0].page_content)
print("--------------------------------------------------------------")
print(type(docs[0].page_content))
print("--------------------------------------------------------------")
print(docs[0].metadata)
print("--------------------------------------------------------------")
print(type(docs[0].metadata))
